import {
  siApacheairflow,
  siApachehive,
  siApachekafka,
  siApacheparquet,
  siApachespark,
  siAnthropic,
  siBitbucket,
  siCmake,
  siCloudflare,
  siCloudflareworkers,
  siConfluence,
  siCplusplus,
  siDatabricks,
  siDjango,
  siDocker,
  siDuckdb,
  siFastapi,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGnubash,
  siGooglebigquery,
  siGooglecloud,
  siGooglecloudcomposer,
  siGooglecloudstorage,
  siGoogledataflow,
  siGoogledataproc,
  siGooglegemini,
  siGooglepubsub,
  siJavascript,
  siJira,
  siJson,
  siJupyter,
  siLinux,
  siLooker,
  siModelcontextprotocol,
  siMysql,
  siNodedotjs,
  siNumpy,
  siObservable,
  siOllama,
  siOpencv,
  siPandas,
  siPosit,
  siPostgresql,
  siPresto,
  siPython,
  siQuarto,
  siR,
  siSqlalchemy,
  siSqlite,
  siTerraform,
  siThemoviedatabase,
  siTodoist,
  siWebassembly,
  type SimpleIcon,
} from "simple-icons";

const LOOKUP: Record<string, SimpleIcon> = {
  python: siPython,
  r: siR,
  javascript: siJavascript,
  pyspark: siApachespark,
  spark: siApachespark,
  "apache spark": siApachespark,
  bash: siGnubash,
  "c++": siCplusplus,
  cmake: siCmake,
  // AWS/Azure/Microsoft brand icons were removed from simple-icons
  bigquery: siGooglebigquery,
  dataproc: siGoogledataproc,
  "gcp dataproc": siGoogledataproc,
  dataflow: siGoogledataflow,
  "gcp dataflow": siGoogledataflow,
  "apache beam": siGoogledataflow,
  "pub/sub": siGooglepubsub,
  "cloud composer": siGooglecloudcomposer,
  "cloud storage": siGooglecloudstorage,
  "cloud logging": siGooglecloud,
  gcp: siGooglecloud,
  databricks: siDatabricks,
  duckdb: siDuckdb,
  kafka: siApachekafka,
  presto: siPresto,
  hive: siApachehive,
  postgresql: siPostgresql,
  "github actions": siGithubactions,
  "gitlab ci": siGitlab,
  gitlab: siGitlab,
  git: siGit,
  github: siGithub,
  bitbucket: siBitbucket,
  terraform: siTerraform,
  docker: siDocker,
  jira: siJira,
  confluence: siConfluence,
  looker: siLooker,
  quarto: siQuarto,
  gemini: siGooglegemini,
  "gemini api": siGooglegemini,
  anthropic: siAnthropic,
  mcp: siModelcontextprotocol,
  "model context protocol": siModelcontextprotocol,
  "model context protocol (mcp)": siModelcontextprotocol,
  ollama: siOllama,
  fastapi: siFastapi,
  django: siDjango,
  pandas: siPandas,
  numpy: siNumpy,
  jupyter: siJupyter,
  mysql: siMysql,
  sqlite: siSqlite,
  sqlalchemy: siSqlalchemy,
  airflow: siApacheairflow,
  linux: siLinux,
  observable: siObservable,
  observablejs: siObservable,
  opencv: siOpencv,
  shiny: siPosit,
  shinylive: siPosit,
  posit: siPosit,
  "posit connect cloud": siPosit,
  parquet: siApacheparquet,
  "tmdb api": siThemoviedatabase,
  "cloudflare workers": siCloudflareworkers,
  cloudflare: siCloudflare,
  webassembly: siWebassembly,
  "node.js": siNodedotjs,
  json: siJson,
  todoist: siTodoist,
};

export function techIconFor(name: string): SimpleIcon | undefined {
  const direct = LOOKUP[name.toLowerCase().trim()];
  if (direct) return direct;
  // Fall back to the first "/" or "(" segment of compound display names
  const base = name.split(/[/(]/)[0].trim().toLowerCase();
  return LOOKUP[base];
}
